### ISSUE TITLE
Monitor Kube Controller Manager with Prometheus

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#1006]
**Goal:**
Create a salt state to deploy Prometheus monitoring for Kube Controller Manager with kubelet using manifests.

**Dependencies:**
- [x] #786
- [x] #997
- [x] #1008

**Details:**
In order to monitor Kube Controller Manager, we need to create the following object (based on kube-prometheus manifests):

ServiceMonitor: https://github.com/coreos/prometheus-operator/blob/v0.24.0/contrib/kube-prometheus/manifests/prometheus-serviceMonitorKubeControllerManager.yaml
Service: A service exposing Kube Controller Manager, i.e.:
```
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
spec:
  selector:
    k8s-app: kube-controller-manager
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252
    protocol: TCP
```

These manifests should maybe not be used as-is, but rather tuned to fit our needs.
Also, these manifests are those for the 0.24.0 version (the one compatible with development/2.0), they must be changed for development/2.1 & development/2.2 branches to use respectively 0.28.0 & 0.29.0 versions.
