### ISSUE TITLE
Put signing policies in the pillar instead of the minion config

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#1059]
Currently we put all signing policies in salt-minion configuration we should use directly the pillar

```
x509_signing_policies:
  kube_apiserver_client_policy:
  - minions: '*'
  - signing_private_key: /etc/kubernetes/pki/ca.key
  - signing_cert: /etc/kubernetes/pki/ca.crt
  - keyUsage: critical digitalSignature, keyEncipherment
  - extendedKeyUsage: clientAuth
  - days_valid: 365
  kube_apiserver_server_policy:
  - minions: '*'
  - signing_private_key: /etc/kubernetes/pki/ca.key
  - signing_cert: /etc/kubernetes/pki/ca.crt
  - keyUsage: critical digitalSignature, keyEncipherment
  - extendedKeyUsage: serverAuth
  - days_valid: 365
  etcd_client_policy:
  - minions: '*'
  - signing_private_key: /etc/kubernetes/pki/etcd/ca.key
  - signing_cert: /etc/kubernetes/pki/etcd/ca.crt
  - keyUsage: critical digitalSignature, keyEncipherment
  - extendedKeyUsage: clientAuth
  - days_valid: 365
  etcd_server_client_policy:
  - minions: '*'
  - signing_private_key: /etc/kubernetes/pki/etcd/ca.key
  - signing_cert: /etc/kubernetes/pki/etcd/ca.crt
  - keyUsage: critical digitalSignature, keyEncipherment
  - extendedKeyUsage: serverAuth, clientAuth
  - days_valid: 365
x509_signing_policies:
  front_proxy_client_policy:
  - minions: '*'
  - signing_private_key: /etc/kubernetes/pki/front-proxy-ca.key
  - signing_cert: /etc/kubernetes/pki/front-proxy-ca.crt
  - keyUsage: critical digitalSignature, keyEncipherment
  - extendedKeyUsage: clientAuth
  - days_valid: 365

```
