### ISSUE TITLE
Add template field in Volume to customize PV creation

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#1500]
Likely to be done later, but we should either have some kind of `template` in the `Volume` spec such that one can define `label`s of the `PersistentVolume` that get created (and other fields like `annotations`), as done in the `podSpec` of a `Deployment`, for example, or we should copy over said values from the `Volume` as-is.

_Originally posted by @NicolasT in https://github.com/scality/metalk8s/pull/1470_

**Comment by slaperche-scality** [comment]
I guess we will go for something like that (keeping the structure of the underlying object):

```yaml
apiVersion: storage.metalk8s.scality.com/v1alpha1
kind: Volume
metadata:
  name: kotlet
spec:
  nodeName: bootstrap
  storageClassName: metalk8s-prometheus
  sparseLoopDevice:
    size: 10Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-operator-alertmanager
```
?

Or do we want to flatten the template and remove the `metadata` things (e.g.: if we only support `metadata` fields):
```yaml
apiVersion: storage.metalk8s.scality.com/v1alpha1
kind: Volume
metadata:
  name: kotlet
spec:
  nodeName: bootstrap
  storageClassName: metalk8s-prometheus
  sparseLoopDevice:
    size: 10Gi
  template:
    labels:
      app.kubernetes.io/name: prometheus-operator-alertmanager
```

BTW, do we want to support other fields?
`annotations` maybe?
