### ISSUE TITLE
Kubespray calico ran into gather_facts timeout

### ISSUE THREAD

**Issue by xaf-scality** [scality/metalk8s#1520]
On some platform we encounter a gather_facts timeout for calico
To avoid this here is the fix of vendor/kubespray/cluster.yml

```
- hosts: k8s-cluster:etcd:calico-rr
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    ansible_ssh_pipelining: true
  gather_facts: true
  pre_tasks:
    - name: gather facts from all instances
      setup:
        gather_timeout: 30
      delegate_to: "{{item}}"
      delegate_facts: True
      with_items: "{{ groups['k8s-cluster'] + groups['etcd'] + groups['calico-rr']|default([])|unique }}”

```
