### ISSUE TITLE
Calico's version check is failing

### ISSUE THREAD

**Issue by xaf-scality** [scality/metalk8s#1521]
On MetalK8s 1.1.x this part of code is always failing

./vendor/kubespray/roles/kubernetes/preinstall/tasks/0020-verify-settings.yml

```
- name: "Check that calico version is enought for upgrade"
  assert:
    that:
      - calico_version_on_server.stdout|version_compare('v2.6.5', '>=')
    msg: "Your version of calico is not fresh enough for upgrade. Minimum version v2.6.5"
  when:
    - 'calico_version_on_server.stdout is defined'
    - 'calico_version_on_server.stdout != ""'
    - inventory_hostname == groups['kube-master'][0]
  run_once: yes
```
