### ISSUE TITLE
Decide the TLS termination for the Ingress objects

### ISSUE THREAD

**Issue by charlesprost** [scality/metalk8s#1800]
Relates to #1797 #1798 #1799 

**Component**:

'kubernetes', 'network', 'ingress'

**Why this is needed**:

Because for some components (such as K8S API), we probably want to keep the TLS termination on the component itself (so we use HTTPS while using kubectl).
And for other components (such as the UI), we may want to have HTTP available internally and using HTTPS from the outside.

**What should be done**:

Decide component by component what to do.

**Implementation proposal** (strongly recommended):

**Test plan**:

**Comment by NicolasT** [comment]
Not sure what the question is here...

- For K8s API and SaltAPI, we *need* them to be bound to the control-plane IP of nodes (there's no CNI available when they're deployed, all we have is `hostNetwork`), and as such most definitely require TLS, and the cert chain their clients expect.
- K8s API is accessible to outside consumers (not the UI) on the control-plane network, using TLS, and so is SaltAPI, for any non-UI API interactions with the system (`kubectl`, our CLI,...)

The only 'corner case' is the UI.

Since the UI requires access to K8s API and SaltAPI, and we don't want the user to be forced to accept the certificates they use (which are, and must remain, self-signed), we need them to be accessible through the same channel as the UI. Since these APIs are sensitive, and request include credentials, we need them to be exposed over TLS, but this can be the *same* TLS cert as the one used for the UI (managed by the ingress controller proxy), so there's no issue.

Anyway.

I think the split-up between various tickets that was made isn't right. We don't want to have an *Ingress* for every service separately, because most *are* already accessible from the outside. It's the UI, Grafana and maybe AlertManager we want to expose.

So we need *at most* 3 Ingress objects (in the according namespaces), unless strictly required otherwise.

Every single one of them, I believe, should be using the same host (or can be the only service if we have an ingress controller on the control-plane IP), then do path-based routing between them.

For Grafana and AlertManager, this should be trivial (though we'll likely want to put them behind something like `oidc-proxy` or similar! So we'll really need to tackle the authn topic before exposing any services...). For the UI, it's slightly more complicated because **the UI requires services not in its own namespace to be available as part of its routing structure**.

However, luckily, this is not too much of a concern, thanks to `ExternalName` *Service*s.

So, here's the trick for the UI (though needs cleanup and enhancements):

```yaml
---
kind: Service
apiVersion: v1
metadata:
  name: kubernetes-api
  namespace: metalk8s-ui
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local
  ports:
    - name: https
      port: 443
---
kind: Service
apiVersion: v1
metadata:
  name: salt-api
  namespace: metalk8s-ui
spec:
  type: ExternalName
  externalName: salt-master.kube-system.svc.cluster.local
  ports:
    - name: https
      port: 4507
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-api
  namespace: metalk8s-ui
spec:
  type: ExternalName
  externalName: prometheus-operator-prometheus.metalk8s-monitoring.svc.cluster.local
  ports:
    - name: http
      port: 9090
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metalk8s-ui-api-salt
  namespace: metalk8s-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: metalk8s.example.com
    http:
      paths:
      - path: /api/salt(/|$)(.*)
        backend:
          serviceName: salt-api
          servicePort: 4507
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metalk8s-ui-api-kubernetes
  namespace: metalk8s-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: metalk8s.example.com
    http:
      paths:
      - path: /api/kubernetes(/|$)(.*)
        backend:
          serviceName: kubernetes-api
          servicePort: 443
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metalk8s-ui-api-prometheus
  namespace: metalk8s-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: metalk8s.example.com
    http:
      paths:
      - path: /api/prometheus(/|$)(.*)
        backend:
          serviceName: prometheus-api
          servicePort: 9090
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metalk8s-ui
  namespace: metalk8s-ui
spec:
  tls:
  - hosts:
    - metalk8s.example.com
  rules:
  - host: metalk8s.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: metalk8s-ui
          servicePort: 80
```

This can't be used as-is: we can merge (some of) the *Ingress* objects, ideally into only one, and we should enforce validation of backend TLS certificates (this is off by default). *Ideally*, we only need a single *Ingress* iff we can have Prometheus and the UI use TLS instead of plain HTTP (which, actually, would make sense), using self-signed certificates (these are *never* exposed to a user directly), at which point we can then validate them from the ingress proxy as well.


To resume.

I think we should start by deploying our second ingress controller on the control-plane network, likely only on `master` nodes, only exposing a TLS port (we'll never want any non-TLS services on this network anyway), and *not* using 443 (this would conflict with `ingress-nginx` if the node is also `infra`/`node`). Question is how to get it to bind to the 'right' IP. Using a specific ingress class, of course (`nginx-control-plane` or so?).

Once this is available, we can
- Change the UI container to use TLS, using a self-signed (from Salt deployment) certificate
- Change the Prometheus deployment to use TLS, using a self-signed (from Salt deployment) certificate

Note: in the above steps, we should create a TLS *Secret* which contains all that's needed from Salt, and use these from the corresponding *Pod*s, *not* put the key/cert/ca in the containers during build or whatnot.

Note: to let Prometheus use TLS, we shouldn't 'hack this in': I believe the `prometheus-operator` chart has built-in support for this (though we'll still need to generate the cert, of course), so as mentioned below, we'll need to change the `values.yaml` and re-render the chart to configure this properly.

- Create a *ConfigMap* in the `metalk8s-ui` namespace containing each of these certs, and make sure they can be used by the ingress controller (can't tell you how, would need to figure that out)
- Create the `ExternalName` *Service*s in the `metalk8s-ui` namespace for K8s API, Salt API and Prometheus
- Create a *single* *Ingress* object in `metalk8s-ui` which uses the ingress class as defined above, uses HTTPS for all its backends, validates their TLS certificate, and exposes the various services on `/` (UI) and `/api/...` (the others), *and* requires the use of TLS at the front-end (easy to set up, the ingress controller already brings a self-signed cert, we can allow to create a *Secret* later which then contains the cert-pair to be used instead).
- Drop the UI configuration file (or most of it), or keep it and hard-code `/api/...` in it instead of the current values (i.e., during Salt deployment).

Then, we want to expose Grafana and AlertManager. This is even easier: I believe the charts we use already support this, so we'd need to alter the corresponding `values.yaml` file, enable generation of the *Ingress* objects (using the right ingress class, enforce TLS, the lot), re-render the chart, and be done with it.
