### ISSUE TITLE
Deploy loki

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2053]
**Component**:

'salt', 'kubernetes'

**Why this is needed**:

To have log aggregation we need a server to aggregate logs

**What should be done**:

Deploy loki helm charts on infra nodes

**Comment by NicolasT** [comment]
Until this ticket is resolved and we install Loki and Promtail (#2054) in a standard MetalK8s installation (or some other log-aggregation service, of course), here's a walktrough on installing and configuring Loki and Promtail in a cluster, and expose it through the MetalK8s-provided Grafana.

## Prerequisites
We assume an up-and-running MetalK8s cluster with some node(s) in the `infra` role (this is where Loki will be running). We'll install the stack using Helm, so you need a valid `KubeConfig` to access the cluster, with `cluster-admin` rights (e.g., `admin.conf` as created by MetalK8s).

Loki needs storage to keep the logs, so the nodes on which it will run require `Volume`s to be provisioned.

All container images are pulled from remote registries, so this only works in an _online_ environment.

## Creating a Namespace
We'll install Loki in a custom namespace. This will allow us to remove this Loki installation easily later, when it's superseded by a log aggregation service included with MetalK8s.

```
$ kubectl create ns loki
```

## Provisioning Storage
We need to create a `StorageClass` for Loki, and one or more `Volume`s the service can then use. First, the `StorageClass`. Copy the following in some file, e.g., `loki-storageclass.yml`:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki
mountOptions:
- rw
- discard
parameters:
  fsType: ext4
  mkfsOptions: '["-m", "0"]'
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

Apply this using

```
$ kubectl apply -f loki-storageclass.yml`
```

Then, use the following template to provision one or more `Volume`s. Note, this example uses a `sparseLoopDevice` `Volume` which comes with performance constraints, and is as such not necessarily usable in production environments. Consider using a `rawBlockDevice` instead! YMMV.

On sizing: the template below creates a 20GiB volume. However, this is an arbitrary number, and we can at this point in time not provide any sizing recommendations. When provisioning some `rawBlockDevice`, using larger devices (or more devices) won't hurt.

Refer to [the documentation](https://metal-k8s.readthedocs.io/en/2.4.2/operation/volume_management/volume_creation_deletion_cli.html) for more information about provisioning `Volume`s.

Create one or more files according to the following template (`loki-volume1.yml`):
```yaml
apiVersion: storage.metalk8s.scality.com/v1alpha1
kind: Volume
metadata:
  annotations:
  name: VOLUME_NAME  # TODO: Change this
spec:
  nodeName: NODE_NAME  # TODO: Change this
  sparseLoopDevice:
    size: 20Gi
  storageClassName: loki
```
and apply the file(s) using

```
$ kubectl apply -f loki-volumeN.yml
```

## Installing Helm
(Note: if Zenko is installed on the cluster, you can skip this step)

You'll need Helm to install the Loki stack. This guide uses Helm version 2.16.3 (not 3.x). Refer to [its documentation](https://v2.helm.sh/docs/using_helm/#installing-helm) for guidelines. MetalK8s clusters use RBAC, so make sure to follow the guide creating a `tiller` `ServiceAccount` and the required `ClusterRoleBinding`, and pass the `ServiceAccount` name to the `helm init ...` invocation.

## Configuring the Loki Repository
On your host, run the following commands to configure the Loki charts registry:

```
$ helm repo add loki https://grafana.github.io/loki/charts
$ helm repo update
```

## Installing Loki and Promtail
We can finally install the stack using Helm. First, we'll need a file containing some custom chart template values, e.g., `loki-stack-values.yml`:

```yaml
loki:
  replicas: 1  # TODO: Change if desired (ensuring storage volumes are available)

  config:
    chunk_store_config:
      max_look_back_period: 168h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

  nodeSelector:
    node-role.kubernetes.io/infra: ''

  persistence:
    enabled: true
    size: 20Gi  # TODO: Adjust to desired volume selection size
    storageClassName: loki

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi

  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/bootstrap
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists

promtail:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi

  pipelineStages: []

  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/etcd
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/bootstrap
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/infra
    operator: Exists
    effect: NoSchedule

  volumes:
  - name: pods
    hostPath:
      path: /var/log/pods

  volumeMounts:
  - name: pods
    mountPath: /var/log/pods
    readOnly: true
```

This uses a log retention time of 168h, 20GiB, and relatively low resource requests and limits. These may need to be raised in production environments.

We can now deploy `loki-stack` by executing the following command:

```
$ helm upgrade --install loki --namespace=loki --version 0.32.0 --values loki-stack-values.yml loki/loki-stack
```

Whenever you make changes to `loki-stack-values.yml`, re-run the above command to apply them.

Now, run `kubectl -n loki get pods`, optionally using `-w`, to see all Loki and Promtail `Pod`s getting scheduled and starting. You should eventually see one Promtail `Pod` per cluster node, and a number of Loki `Pod`s based on the `loki.replicas` setting in `loki-stack-values.yml`.

## Exposing Loki through Grafana
We can finally expose Loki through the Grafana UI that comes with your MetalK8s installation. To achieve this, copy the following in a file, e.g., `loki-grafana-datasource.yml`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-stack-grafana-datasource
  namespace: metalk8s-monitoring
  labels:
    grafana_datasource: "1"
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.loki.svc.cluster.local:3100
      version: 1
```

and apply it to the cluster:

```
$ kubectl -n metalk8s-monitoring apply -f loki-grafana-datasource.yml
```

Now, we should restart Grafana to pick up these changes (note: not entirely sure this is required):

```
$ kubectl -n metalk8s-monitoring rollout restart deployment prometheus-operator-grafana
deployment.extensions/prometheus-operator-grafana restarted
$  kubectl -n metalk8s-monitoring rollout status deployment prometheus-operator-grafana
Waiting for deployment "prometheus-operator-grafana" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "prometheus-operator-grafana" rollout to finish: 1 old replicas are pending termination...
deployment "prometheus-operator-grafana" successfully rolled out
```

Finally, open the Grafana UI in a browser. In the menu on the right, select the *Explore* view (the compass-like icon). Next, in the dropdown at the top left, switch to the *Loki* datasource.
