### ISSUE TITLE
etcd initial-cluster Contains Duplicate Entries

### ISSUE THREAD

**Issue by bkettler** [scality/metalk8s#2083]
After expanding from a 2 node MetalK8s cluster to a 3 node MetalK8s the initial-cluster value in etcd.yaml contains duplicate URLs on the new host.

`        - --initial-cluster==https://10.25.144.162:2380,app-1=https://10.25.144.151:2380,storage-1=https://10.25.144.161:2380,storage-2=https://10.25.144.162:2380
`

When duplicate entries are defined the the etcd container will repeatedly fail to start with the following error.

`2019-11-27 17:29:40.350157 C | etcdmain: initial cluster =https://10.25.144.162:2380,app-1=https://10.25.144.151:2380,storage-1=https://10.25.144.161:2380,storage-2=https://10.25.144.162:2380 has duplicate url
`

Version : MetalK8s 2.4.1

**Comment by gdemonet** [comment]
Thanks for the bug report!

It is a surprising issue, as the code we have on our side is supposed to handle deduplication. It seems something went wrong in a strange way, as the duplicated peer is definitely missing half of the declaration (no name before the `=` sign).

We will add an extra safeguard, but I don't understand why it happened. Anything peculiar in your setup that might give us a hint @bkettler?

**Comment by NicolasT** [comment]
The duplicate IP address in there is quite surprising as well...

**Comment by NicolasT** [comment]
@bkettler What could help us to debug: could you execute the following and provide the output of:

```sh
salt-call pillar.items metalk8s:etcd:members
```
(as `root`) on your 'bootstrap' node, as well as something along the following lines:

```
[root@bootstrap ~]# kubectl -n kube-system get pods -l component=etcd
NAME             READY   STATUS    RESTARTS   AGE
etcd-bootstrap   1/1     Running   4          2d

[root@bootstrap ~]# kubectl -n kube-system exec -ti etcd-bootstrap sh -- -c "ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key member list"
37bacaf3fa2d1df9, started, bootstrap, https://172.21.254.13:2380, https://172.21.254.13:2379
```
where in the second command, you replace `etcd-bootstrap` with the Pod name as found in the output of the first command.

Thanks!

**Comment by bkettler** [comment]
@gdemonet the only thing unique about this installation is that the additional nodes are being installed from the CLI and not the UI. I used the following node definition.

```
apiVersion: v1
kind: Node
metadata:
  name: storage-12
  annotations:
    metalk8s.scality.com/ssh-user: "root"
    metalk8s.scality.com/ssh-port: "22"
    metalk8s.scality.com/ssh-host: "10.25.144.172"
    metalk8s.scality.com/ssh-key-path: "/etc/metalk8s/pki/salt-bootstrap"
    metalk8s.scality.com/ssh-sudo: "false"
  labels:
    metalk8s.scality.com/version: '2.4.1'
    node-role.kubernetes.io/master: ''
    node-role.kubernetes.io/etcd: ''
    node-role.kubernetes.io/infra: ''
    node-role.kubernetes.io/node: ''
```

@NicolasT here is the output you requested.

```
[root@app-1 scality]# kubectl -n kube-system get pods -l component=etcd
NAME             READY   STATUS             RESTARTS   AGE
etcd-app-1       1/1     Running            16         5d22h
etcd-storage-1   1/1     Running            2          5d17h
etcd-storage-2   0/1     CrashLoopBackOff   1397       4d22h
[root@app-1 scality]# kubectl -n kube-system exec -ti etcd-app-1 sh -- -c "ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key member list"
464fb5466ccf32b0, started, storage-1, https://10.25.144.161:2380, https://10.25.144.161:2379
8fe609fefda908ff, started, app-1, https://10.25.144.151:2380, https://10.25.144.151:2379
dde9c74a54a50cb7, unstarted, , https://10.25.144.162:2380,
[root@app-1 scality]# kubectl exec -it -n kube-system -c salt-master --kubeconfig /etc/kubernetes/admin.conf salt-master-app-1 bash                                                                                                          [root@app-1 /]# salt-call pillar.items metalk8s:etcd:members
bash: salt-call: command not found
[root@app-1 /]# exit
exit
command terminated with exit code 127
[root@app-1 scality]# salt-call pillar.items metalk8s:etcd:members
local:
    ----------
    metalk8s:etcd:members:
        - =https://10.25.144.162:2380
        - app-1=https://10.25.144.151:2380
        - storage-1=https://10.25.144.161:2380
```
