### ISSUE TITLE
Downgrade use the wrong saltenv if fail after bootstrap downgrade

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#2408]
**Component**:

'scripts', 'lifecycle'

**What happened**:

When downgrading if for whatever reason downgrade fail after bootstrap node downgrade the saltenv used when launching new downgrade will use the bootstrap node version which is wrong and downgrade precheck state will fail.

```
bootstrap_master:
----------
          ID: Invalid saltenv "metalk8s-2.4.2" consider using "metalk8s-2.5.0-dev"
    Function: test.fail_without_changes
      Result: False
     Comment: Failure!
     Started: 07:58:01.311970
    Duration: 0.868 ms
```

We cannot force this saltenv from the script as we have `SALTENV=""` at the beginning of the script

**What was expected**:

Use the right version for saltenv and ability to force it.

**Steps to reproduce**

Run downgrade one multi-node cluster and fail right after the downgrade of the bootstrap one

Or just manually change the bootstrap node version

**Resolution proposal** (optional):

Two-points:
- Ability to force the SALTENV if needed
- Use the script version `@@VERSION` instead of bootstrap version in the downgrade script

IMO this two-point should also be done in the upgrade script 

----

For me this ticket is blocker for 2.5.0 release
