### ISSUE TITLE
[docs]: Missing Salt-SSH annotations details on Node manifests creation

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2440]
**Component**: docs

**What happened**:

In the Installation Guide, when [creating Nodes using the CLI](https://metal-k8s.readthedocs.io/en/latest/installation/expansion.html#adding-a-node-from-the-command-line), we get this example manifest:

```yaml
apiVersion: v1
kind: Node
metadata:
  name: <node_name>
  annotations:
    metalk8s.scality.com/ssh-key-path: /etc/metalk8s/pki/salt-bootstrap
    metalk8s.scality.com/ssh-host: <node control plane IP>
    metalk8s.scality.com/ssh-sudo: 'false'
  labels:
    metalk8s.scality.com/version: '2.6.0-dev'
    <role labels>
spec:
  taints: <taints>
```

And no further explanation regarding the Salt-SSH annotations (hence, no mention of the `ssh-user` annotation, and its default value being `root`).

**What was expected**:

A user would probably need to adjust these values depending on its environment. The documentation should make the intent of each annotation clear, and give a simple example for providing a non-root user.
