### ISSUE TITLE
Get the alerts for the specific resource

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2502]
**Component**: alerts

**Why this is needed**:
In UI, I want to gather all the alerts for a specific resource (Node/Volume), so that when I access a specific node/volume page, I can have an alert list for this specific resource.

**What should be done**:
Add labels!!!

1. For all the alerts related to the volume, I would like to add a label for alerts to specify the resource.
2. I would like to add a label to know who(which volume/which node) triggers this alert.

We could add the label in the alert to specify which volume trigger this alert.
```
  - alert: KubePersistentVolumeErrors
      annotations:
        message: The persistent volume {{`{{ $labels.persistentvolume }}`}} has status {{`{{ $labels.phase }}`}}.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeerrors
      expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending",job="kube-state-metrics"} > 0
      for: 5m
      labels:
        severity: critical
        volume:
          volume_name: {{`{{ $labels.persistentvolume }}`}}
```
**Implementation proposal** (strongly recommended):
TBD

**Test plan**:
TBD
