### ISSUE TITLE
Update cluster and service operational guide to expose CSC defaults, CSC addition steps and examples

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2522]
**Component**:

'docs', 'csc'

**Why this is needed**:

Since the rework of Cluster and service configuration design was introduced here: https://github.com/scality/metalk8s/pull/2501, CSC ConfigMaps do no longer hold default values. We need to include documentation that allows MetalK8s administrator to add new Service configurations within the provided CSC ConfigMaps and also expose the default CSCs.
: 

**What should be done**:

In the CSC section of the docs under Operational Guide, add documentation explaining the supported MetalK8s service configs and the current service config defaults already deployed. 

Provide examples that will guide Metalk8s administrators in adding service configs in the right allocated slots.
```
        example configuration
          config.yaml: |-
            apiVersion: addons.metalk8s.scality.com
            kind: DexConfig
            spec:
              # Configure the Dex Deployment
              deployment:
                replicas: 2
```
**Implementation proposal** (strongly recommended):

**Test plan**:
