### ISSUE TITLE
Expose Alertmanager through Ingress

### ISSUE THREAD

**Issue by ChengYanJin** [scality/metalk8s#2636]
**Component**:
monitoring 

**Why this is needed**:
I would like to access the Alertmanager service from UI. But we didn't expose it through Ingress yet.

**What should be done**:
Expose the Alertmanager service through Ingress

**Implementation proposal** (strongly recommended):
1. Create Alertmanager service 
```
kind: Service
apiVersion: v1
metadata:
  name: alertmanager-api
  namespace: metalk8s-ui
  labels:
    app: metalk8s-ui
    app.kubernetes.io/managed-by: salt
    app.kubernetes.io/name: metalk8s-ui
    app.kubernetes.io/part-of: metalk8s
    heritage: metalk8s
spec:
  type: ExternalName
  externalName: prometheus-operator-alertmanager.metalk8s-monitoring.svc.cluster.local
  ports:
    - name: http
      port: 9093
```
 2. Edit the new ingress:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metalk8s-ui-proxies-http
  namespace: metalk8s-ui
  labels:
    app: metalk8s-ui
    app.kubernetes.io/managed-by: salt
    app.kubernetes.io/name: metalk8s-ui
    app.kubernetes.io/part-of: metalk8s
    heritage: metalk8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "nginx-control-plane"
spec:
  rules:
  - http:
      paths:
      - path: /api/prometheus(/|$)(.*)
        backend:
          serviceName: prometheus-api
          servicePort: 9090
      - path: /api/alertmanager(/|$)(.*)
        backend:
          serviceName: alertmanager-api
          servicePort: 9093
```

Then we should be able to access the AlertManger UI by:
`https://{ip}:8443/api/alertmanager`

**Test plan**:
TBD
