### ISSUE TITLE
Add support for raw (non-formatted) volume in the UI

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#2660]
**Component**:

ui

**Why this is needed**:

We now support formatted and non-formatted volume, but from the UI we can only create formatted volume.

**What should be done**:

On the volume creation page, add way (a dropdown?) to select the volume mode (either `Filesystem` or `Block`, default being `Filesystem`).

Not sure if we want to expose k8s vocabulary (`Filesystem`/`Block`) or another term (`Formatted`/`Non-formatted`)? To be defined.

**Implementation proposal**:

- add a way to get the volume mode from the user
- then use this information to generate the CRD, e.g.:

```yaml
apiVersion: storage.metalk8s.scality.com/v1alpha1
kind: Volume
metadata:
  name: foo
spec:
  nodeName: master-1
  storageClassName: metalk8s-prometheus
  mode: Block // or   mode: Filesystem
  rawBlockDevice:
    devicePath: "/dev/vdb"
```

**Test plan**:

TBD
