### ISSUE TITLE
Deploy Grafana datasource for Loki

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2683]
**Component**: salt

**Why this is needed**:
See #2668 

**What should be done**:
Add a grafana datasource for Loki

**Implementation proposal** (strongly recommended):
To be able to query logs from Loki, we need to add a Grafana datasource, this is done adding a ConfigMap `loki-grafana-datasource` in `metalk8s-logging` (to be checked, maybe it does not work outside `metalk8s-monitoring` namespace) Namespace as follows:

```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: loki-grafana-datasource
    namespace: metalk8s-monitoring
    labels:
      grafana_datasource: "1"
  data:
    loki-datasource.yaml: |-
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.loki.svc.cluster.local:3100
        version: 1
```

**Test plan**: n/a
