### ISSUE TITLE
Make Loki configuration customizable with CSC

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2684]
**Component**: salt, loki

**Why this is needed**:
To be able to customize Loki configuration in a persistent way.

**What should be done**:
Expose Loki configuration through a CSC ConfigMap.

**Implementation proposal** (strongly recommended):
Loki's configuration is stored as a Secret.
Since we do not have Operator and CRs for Loki, we will use the CSC mechanism to provide the interface for customization, with a ConfigMap ``metalk8s-loki-config`` in the ``metalk8s-logging`` Namespace.

The CSC ``ConfigMap`` will look like the followings:

```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: metalk8s-loki-config
    namespace: metalk8s-logging
  data:
    config.yaml: |-
      apiVersion: addons.metalk8s.scality.com
      kind: LokiConfig
      spec:
        deployment:
          replicas: 1
        config:
          auth_enabled: false
          chunk_store_config:
            max_look_back_period: 168h
          ingester:
            chunk_block_size: 262144
            chunk_idle_period: 3m
            chunk_retain_period: 1m
            [...]
```

With default values fetched from a YAML file as it is already done for Dex, Alertmanager and Prometheus.

**Test plan**:
