### ISSUE TITLE
Deploy Grafana dashboards for Loki

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2721]
**Component**: salt, monitoring

**Why this is needed**:
To retrieve important metrics of Loki but also be able to easily read logs 

**What should be done**:
Deploy 2 Grafana dashboards for Loki, one for the operational view and the second one to retrieve the logs.

**Implementation proposal** (strongly recommended):

Add a ConfigMap `loki-logs-dashboard` in Namespace `metalk8s-monitoring` (to be checked, maybe we can deploy those dashboards in `metalk8s-logging` namespace, which would be better):
```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: loki-logs-dashboard
    namespace: metalk8s-monitoring
    labels:
      grafana_dashboard: "1"
  data:
    loki-logs.json: <DASHBOARD DEFINITION>
```

This dashboard will be based on what we can find in Grafana repository: https://github.com/grafana/loki/blob/master/production/loki-mixin/dashboard-loki-logs.json

Add a ConfigMap `loki-operational-dashboard` in Namespace `metalk8s-monitoring`:
```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: loki-operational-dashboard
    namespace: metalk8s-monitoring
    labels:
      grafana_dashboard: "1"
  data:
    loki-operational.json: <DASHBOARD DEFINITION>
```

This dashboard definition can be found here: https://github.com/grafana/loki/blob/master/production/loki-mixin/dashboard-loki-operational.json

**Test plan**:
Manual testing, just try to connect to the dashboards and see if information are there.
