### ISSUE TITLE
Solution import falsely reports the presence of a Solution UI & Solution Operator image in pillars

### ISSUE THREAD

**Issue by Ebaneck** [scality/metalk8s#2788]
**Component**:

'salt', 'solutions', 'keycloak'

**What happened**:

Importing a Solution (Keycloak) falsely reports the presence of a Keycloak operator and Keycloak UI images in the pillars.

**What was expected**:

Since the given solution has no Operator or UI images, the pillar entry should be empty.

**Steps to reproduce**
- Bootstrap a cluster with MetalK8s 2.5.1 released version
- Obtain a solution ISO (artifacts)
- Import the Solution ISO using the documented procedure [here](https://metal-k8s.readthedocs.io/en/latest/developer/solutions/deploy.html?highlight=activate#import-a-solution)
- Locate the imported Solution within the pillars using `salt-call pillar.get metalk8s:solutions`

Here is my solution manifest.yaml
```
[root@bootstrap key]# cat manifest.yaml 
apiVersion: solutions.metalk8s.scality.com/v1alpha1
kind: Solution
metadata:
  annotations:
    solutions.metalk8s.scality.com/build-host: kw017-prod-ringx-backend-0-69-47
    solutions.metalk8s.scality.com/build-timestamp: '2020-09-11T08:40:32Z'
    solutions.metalk8s.scality.com/development-release: '1'
    solutions.metalk8s.scality.com/display-name: Keycloak Solution
    solutions.metalk8s.scality.com/git-revision: b05de72
  labels: {}
  name: keycloak-solution
spec:
  images:
  - postgresql:11.9.0-debian-10-r1
  - keycloak:11.0.1
  - busybox:1.31.1
  - postgresql-exporter:0.8.0-debian-10-r166
  operator:
    image: {}
  version: 0.1.0-dev

```

Here is the reported pillar info 
```
[root@bootstrap key]# salt-call pillar.get metalk8s:solutions
local:
    ----------
    available:
        ----------
        keycloak-solution:
            |_
              ----------
              active:
                  False
              archive:
                  /home/centos/keycloak-solution-0.1.0-dev.iso
              id:
                  keycloak-solution-0.1.0-dev
              manifest:
                  ----------
                  apiVersion:
                      solutions.metalk8s.scality.com/v1alpha1
                  kind:
                      Solution
                  metadata:
                      ----------
                      annotations:
                          ----------
                          solutions.metalk8s.scality.com/build-host:
                              kw017-prod-ringx-backend-0-69-47
                          solutions.metalk8s.scality.com/build-timestamp:
                              2020-09-11T08:40:32Z
                          solutions.metalk8s.scality.com/development-release:
                              1
                          solutions.metalk8s.scality.com/display-name:
                              Keycloak Solution
                          solutions.metalk8s.scality.com/git-revision:
                              b05de72
                      labels:
                          ----------
                      name:
                          keycloak-solution
                  spec:
                      ----------
                      customApiGroups:
                      images:
                          - postgresql:11.9.0-debian-10-r1
                          - keycloak:11.0.1
                          - busybox:1.31.1
                          - postgresql-exporter:0.8.0-debian-10-r166
                      operator:
                          ----------
                          image:
                              ----------
                              name:
                                  keycloak-solution-operator
                              tag:
                                  0.1.0-dev
                      ui:
                          ----------
                          image:
                              ----------
                              name:
                                  keycloak-solution-ui
                              tag:
                                  0.1.0-dev
                      version:
                          0.1.0-dev
              mountpoint:
                  /srv/scality/keycloak-solution-0.1.0-dev
              name:
                  keycloak-solution
              version:
                  0.1.0-dev
    config:
        ----------
        active:
            ----------
        apiVersion:
            solutions.metalk8s.scality.com/v1alpha1
        archives:
            - /home/centos/keycloak-solution-0.1.0-dev.iso
        kind:
            SolutionsConfiguration
    environments:
        ----------

```
**Resolution proposal** (optional):

TBD
