### ISSUE TITLE
Add linting check for commit messages

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#2935]
**Component**: git

**Why this is needed**:

We have decided of a format for our Git commit messages (see [our best practices](https://metal-k8s.readthedocs.io/en/latest/developer/development/commit.html)), but it is not enforced yet.

**What should be done**:

We want to enforce this format through a linting check.

**Implementation proposal** (strongly recommended):

- Add some GitHub Action to enforce this check on all PRs (something like:

```yaml
# .github/workflows/commitlint.yml
---
name: "Lint Commit Messages"
"on":
  - "pull_request"jobs:
  commitlint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "wagoid/commitlint-github-action@v2.1.0"
```

credits to @NicolasT)

- Add the exact same linter to Eve steps (as part of our `lint` stage), to make sure an Eve `pre-merge` run is self-sufficient

**Test plan**:

Invalid commit messages should never land in this repository anymore.
