### ISSUE TITLE
Make Prometheus retention period configurable

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#2953]
**Component**: monitoring, csc, salt

**Why this is needed**:
To allow user to change the retention period of Prometheus (which is 10 days by default).

**What should be done**:
Make it configurable through CSC ConfigMap `metalk8s-prometheus-config`.
We should also update documentation to explain how to customize retention.

**Implementation proposal** (strongly recommended):
Add a default in `salt/metalk8s/addons/prometheus-operator/config/prometheus.yaml`:
```
apiVersion: addons.metalk8s.scality.com
kind: PrometheusConfig
spec:
  config:
    retention: 10d
```
Then render `salt/metalk8s/addons/prometheus-operator/deployed/chart.sls` using this entry:
```
       release: prometheus-operator
   portName: web
   replicas: {% endraw -%}{{ prometheus.spec.deployment.replicas }}{%- raw %}
-  retention: 10d
+  retention: {% endraw -%}{{ prometheus.spec.config.retention }}{%- raw %}
   routePrefix: /
   ruleNamespaceSelector: {}
   ruleSelector:
```
The option will then be automatically configurable through CSC.

**Bonus:** we could also expose `retentionSize` (disabled by default) which is as the name suggests a retention based on the size, both options can be set at the same time. If we do so, we need to warn the user in the documentation that actually Prometheus does not take in account the WAL size, so the required size is greater than `retentionSize` (add at least 10% to be safe).

**Test plan**:
