### ISSUE TITLE
Downgrade fail at the very end when deleting old prometheus rules

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#3027]
**Component**:

'salt', 'downgrade'

**What happened**:

When downgrading at the very end we clean up Prometheus rules no longer needed but the first time we call this state it fail

```
----------
          ID: Delete old PrometheusRule prometheus-operator-kube-apiserver-availability.rules
    Function: metalk8s_kubernetes.object_absent
        Name: prometheus-operator-kube-apiserver-availability.rules
      Result: False
     Comment: The object is still present after 10 check attempts
     Started: 13:41:12.681860
    Duration: 100220.814 ms
     Changes:   
----------
```

NOTE: Launching the downgrade again work

**What was expected**:

No failure

**Steps to reproduce**

Try to downgrade from 2.7.0 to 2.6.0 (it may do the same when doing other downgrades)

**Resolution proposal** (optional):

To be investigate
