### ISSUE TITLE
Upgrade from 2.6.x to 2.7.0 fails when cleaning sparse loop volumes

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#3064]
<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!

If the matter is security related, please disclose it privately to moonshot-platform@scality.com
-->

**Component**: salt, upgrade, storage

**Summary**:

When running the `upgrade.sh` script to upgrade a MetalK8s 2.6.x cluster to 2.7.0, the `Upgrading all nodes one by one` step will abort for each node which has no `SparseLoopDevice` Volume provisioned, during the `metalk8s.volumes.cleanup` state execution. It will show an error similar to:

```
                        ID: Cleanup existing loop devices                                                                                                                                                                                     
                  Function: salt.state                                                                                                                                                                                                        
                    Result: False                                                                                                                                                                                                             
                   Comment: Run failed on minions: metalk8s-control-plane-02                                                                                                                                                                  
                   Started: 23:39:50.586427                                                                                                                                                                                                   
                  Duration: 2838.153 ms                                                                                                                                                                                                       
                   Changes:                                                                                                                                                                                                                   
                            metalk8s-control-plane-02:                                                                                                                                                                                        
                                Data failed to compile:                                                                                                                                                                                       
                            ----------                                                                                                                                                                                                        
                                Rendering SLS 'metalk8s-2.7.0:metalk8s.volumes.cleanup' failed: Jinja variable 'target_is_2_7' is undefined 
```

The only available workaround is to restart the `upgrade.sh` script, once per failing node, until completion.
