### ISSUE TITLE
Flakies and error in cypress Solutions tests

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#3109]
**Component**:

'cypress', 'flaky'

**What happened**:

1-  From time to time on Solution cypress tests, we get failure on authentication
![image](https://user-images.githubusercontent.com/41334261/107671501-33813f00-6c94-11eb-9424-1292c40969d1.png)

2- Solution version is wrong in cypress test
```
ui/cypress/integration/e2e/Solutions/steps.js:6:const solutionVersion = '0.1.0-dev';
ui/cypress/integration/e2e/Solutions/steps.js:7:const upgradeSolutionVersion = '0.1.1-dev';
```

```
eve/main.yml:853:          name: Set Example Solution version property
eve/main.yml-854-          property: example_solution_version
eve/main.yml-855-          value: 1.0.0
eve/main.yml-856-      - SetProperty:
eve/main.yml:857:          name: Set Example Solution version next property
eve/main.yml-858-          property: example_solution_version_next
eve/main.yml-859-          value: 1.0.1
```

**What was expected**:

1- Less flakies on authentication cypress tests

2- Solution version should be configurable from cypress command line 

**Steps to reproduce**

Try to run post-merge for solutions

**Resolution proposal** (optional):

1- No idea

2- No idea
But ideally, we should be able to give the example solution versions and name from CLI (either from an args or environment variable)
Something like this
```
SOLUTION_NAME="example-solution" SOLUTION_VERSION="1.0.0" SOLUTION_VERSION_NEXT="1.0.1" npm run test:e2esolutions
```
Or in eve
```
  - ShellCommand:
      name: Run Solution UI tests on Bastion
      env:
        TEST_FILTER: "e2esolutions"
        TARGET_URL: "https://%(prop:bootstrap_control_plane_ip)s:8443"
        SOLUTION_NAME: "%(prop:solution_name:-example-solution)s"
        SOLUTION_VERSION: "%(prop:example_solution_version)s"
        SOLUTION_VERSION_NEXT: "%(prop:example_solution_version_next)s"
      command: >
        ssh -F ssh_config bastion --
        "cd metalk8s/ui &&
        SOLUTION_NAME=$SOLUTION_NAME SOLUTION_VERSION=$SOLUTION_VERSION 
SOLUTION_VERSION_NEXT=$SOLUTION_VERSION_NEXT CYPRESS_BASE_URL=$TARGET_URL npm run test:$TEST_FILTER"
      workdir: build/eve/workers/openstack-terraform/terraform/
      haltOnFailure: true
```
