### ISSUE TITLE
UI: Support LVMLogicalVolume volume in the metalk8s-ui

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#3244]
**Component**:

ui

**Why this is needed**:

`LVMLogicalVolume` support get added in https://github.com/scality/metalk8s/pull/3220 in storage operator

**What should be done**:

- [x] Properly listing `LVMLogicalVolume` volume in the UI (in #3316)
- [x] Ability to create that kind of volumes from the UI

NOTE: Documentation may need to be updated a bit to reflect this UI change

**Implementation proposal** (strongly recommended):

Volume object example: 
```
apiVersion: storage.metalk8s.scality.com/v1alpha1
kind: Volume
metadata:
  name: my_volume
spec:
  nodeName: my_node
  storageClassName: metalk8s
  lvmLogicalVolume:
    size: 10Gi
    vgName: my-vg
```

New fields in `lvmLogicalVolume`:
- `size` exactly the same as `sparseLoopDevice` size
- `vgName` the LVM Volume Group name to create the LVM LogicalVolume (Note: a VG could (and will) be used by several LVMLogicalVolume)

**Test plan**:
