### ISSUE TITLE
[doc] PrometheusRules require specific labels

### ISSUE THREAD

**Issue by lavigne958** [scality/metalk8s#3293]
**Component**:

Documentation - Prometheus

**Why this is needed**:
Without it the alert rules are not taken by prometheus operator

**What should be done**:
Add documentation about these required labels.

**Implementation proposal** (strongly recommended):

> In order for the new alerting rule to be added by the prometheus operator the following labels must be set with the following values:

```yaml
// Required for prometheus discovery
- app:                    "prometheus-operator"
- app.kubernetes.io/name: "prometheus-operator"
- role:                   "alert-rules"
```

**Test plan**:
Add new alerting rule and ommit one of the above labels.
