### ISSUE TITLE
Expose NGINX ingress controller metrics and scrape them with Prometheus

### ISSUE THREAD

**Issue by alexandre-allard** [scality/metalk8s#3375]
**Component**: charts, salt

**Why this is needed**:
To be able to correctly monitor NGINX processes.

**What should be done**:
Expose ingress-nginx controller metrics, then scrape them using Prometheus.

**Implementation proposal** (strongly recommended):

• Tune the ingress-nginx Helm chart configuration file `charts/ingress-nginx.yaml`:
  - enable metrics
```yaml
controller:
  metrics:
    enabled: true
```
  - enable `ServiceMonitor` object deployment
```yaml
controller:
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        metalk8s.scality.com/monitor: ''
```
•  We could also add some PrometheusRules if needs be, some examples are already present in the chart:
```yaml
# These are just examples rules, please adapt them to your needs
- alert: NGINXConfigFailed
  expr: count(nginx_ingress_controller_config_last_reload_successful == 0) > 0
  for: 1s
  labels:
    severity: critical
  annotations:
    description: bad ingress config - nginx config test failed
    summary: uninstall the latest ingress changes to allow config reloads to resume
- alert: NGINXCertificateExpiry
  expr: (avg(nginx_ingress_controller_ssl_expire_time_seconds) by (host) - time()) < 604800
  for: 1s
  labels:
    severity: critical
  annotations:
    description: ssl certificate(s) will expire in less then a week
    summary: renew expiring certificates to avoid downtime
- alert: NGINXTooMany500s
  expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
  for: 1m
  labels:
    severity: warning
  annotations:
    description: Too many 5XXs
    summary: More than 5% of all requests returned 5XX, this requires your attention
- alert: NGINXTooMany400s
  expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"4.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
  for: 1m
  labels:
    severity: warning
  annotations:
    description: Too many 4XXs
```
 •  We may also want to deploy Grafana dashboards (e.g. https://github.com/kubernetes/ingress-nginx/tree/master/deploy/grafana/dashboards)

**Test plan**:
