### ISSUE TITLE
Expose `anti-affinity` for coredns deployment

### ISSUE THREAD

**Issue by TeddyAndrieux** [scality/metalk8s#3574]
**Component**:

'kubernetes', 'dns'

**Why this is needed**:

Today we deploy coredns with 2 replicas and no affinity which means that all coredns may sit on the same node, which mean no HA for the Kubernetes DNS which likely has an impact on the workload running in the cluster.

**What should be done**:

In order to have HA of coredns we need to make sure the coredns replica sits in different "failure zone". 
But this cannot be done automatically and need to be input from the user, so we need to expose a way to change this.

We likely want to also expose the number of coredns replicas.

**Implementation proposal** (strongly recommended):

Add an entry in the bootstrap config for coredns so that user can input:
- the number of replicas for coredns (default to 2)
- the topologyKey to use for anti-affinity (soft and hard) of coredns Pods
  suggested default (TBD) (soft anti-affinity on hostname):
  ```yaml
   podAntiAffinity:
     preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 100
       podAffinityTerm:
         labelSelector:
           matchLabels:
             k8s-app: kube-dns
         namespaces:
         - kube-system
         topologyKey: kubernetes.io/hostname
  ```

Since coredns pod will not be re-scheduled during the life of the platform in order to be sure our "soft" anti-affinity gets applied when it's possible we will need to trigger a "rollout restart" of the coredns when we expand MetalK8s cluster with a new master node.

Check kubernetes docs for more information about affinity and anti-affinity https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
