### ISSUE TITLE
error in "etcd : Gen_certs | add CA to trusted CA dir" -> ca.pem does not exist.

### ISSUE THREAD

**Issue by mastachand** [scality/metalk8s#442]
Running 1.0.0 on centos 7.4.1708

I get this:

```
TASK [etcd : Gen_certs | add CA to trusted CA dir] *****************************
fatal: [node-03]: FAILED! => {"changed": false, "msg": "Source /etc/ssl/etcd/ssl/ca.pem not found"}
fatal: [node-02]: FAILED! => {"changed": false, "msg": "Source /etc/ssl/etcd/ssl/ca.pem not found"}
```
running

```
ansible-playbook -i ../k8s-cluster/inventory -b playbooks/deploy.yml -e metalk8s_ansible_hardening_enabled=false -vvvv
```

Inventory:

```
node-01 ansible_host=node-01 ansible_user=root
node-02 ansible_host=node-02 ansible_user=root
node-03 ansible_host=node-03 ansible_user=root

[bigserver]
node-01

[smallserver]
node-02
node-03

[kube-master]
node-01
node-02
node-03

[etcd]
node-01
node-02
node-03


[kube-node:children]
bigserver
smallserver

[k8s-cluster:children]
kube-node
kube-master
```

kube-node.yml:
```
metalk8s_lvm_default_vg: False
metalk8s_lvm_vgs: ['vg_metalk8s']
metalk8s_lvm_drives_vg_metalk8s: ['/dev/vdb']
metalk8s_lvm_lvs_vg_metalk8s:
  lv01:
    size: 100G
  lv02:
    size: 54G
  lv03:
    size: 22G
  lv04:
    size: 12G
  lv05:
    size: 10G
  lv06:
    size: 6G
```

bigserver.yml:
```
metalk8s_lvm_lvs_vg_metalk8s:
  lv01:
    size: 100G
  lv02:
    size: 54G
  lv03:
    size: 22G
  lv04:
    size: 12G
  lv05:
    size: 10G
  lv06:
    size: 6G
```

smallserver.yml:
```
metalk8s_lvm_lvs_vg_metalk8s:
  lv01:
    size: 54G
  lv02:
    size: 22G
  lv03:
    size: 12G
  lv04:
    size: 10G
  lv05:
    size: 6G
```

thanks. Attached is the ansible log file.

[metalk8s_ansible.log](https://github.com/scality/metalk8s/files/2470550/metalk8s_ansible.log)
