### ISSUE TITLE
Add more labels for control-plane Pods

### ISSUE THREAD

**Issue by gdemonet** [scality/metalk8s#668]
As was done for the `registry` or the `salt-master` Pods, we would like to add extra labels to our Pods for the control plane:

```yaml
metadata:
  labels:
    app: {{ component_name }}
    app.kubernetes.io/name: {{ component_name }}
    app.kubernetes.io/version: {{ component_version }}
    app.kubernetes.io/component: {{ component_name }}
    heritage: metalk8s
    app.kubernetes.io/part-of: metalk8s
    app.kubernetes.io/managed-by: salt
```
