### ISSUE TITLE
Define various states, highstates, runners,...

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#742]
In 2.0.0-alpha1, we developed a couple of states, and a script to invoke those states in a certain order.

We need to figure out a more holistic design of the various states that should exist, how they relate, which state incorporates others,..., then define what the `highstate` of various kinds of nodes should be, such that we can invoke the related Salt state directly, and finally which orchestration/runners we need to perform certain one-off tasks (playbook-style).

I'll create a Google doc to capture this at first, after which we can turn it into a document maintained in this repository.

Very much relates to #735, #736, #626 and likely some others.

**Comment by NicolasT** [comment]
This list, currently WiP in an internal doc, should be brought in sync with the deployment diagram.

**Comment by NicolasT** [comment]
Our use of orchestration is becoming a bit unwieldy, and not strictly required: many of the things we aim to achieve are in the end simple 'states', and nodes (both workload-plane as well as control-plane) can simply be brought up to 'highstate', as long as we have the right 'top' files defined.

(Side note: of course, certain 'orchestrations' where one-time imperative steps are required, like bringing an `etcd` node into the cluster, is still required).

Here's a sketch as to how to proceed:

- We should start declaring software versions on nodes. I.e. an annotation, `metalk8s.scality.com/version`, which denotes the desired version of MetalK8s to run on said node
- We should extend our 'custom pillar' to retrieve node/minion information from Kubernetes, and fill in fields accordingly. Some examples:

  * `metalk8s:role` can be a list derived from `node-role.kubernetes.io/master`, `node-role.kubernetes.io/etcd` and similar labels
  * `metalk8s:version` can be easily derived from the annotation mentioned above

Once this pillar data is available, we can, for every 'file root', i.e. every version of MetalK8s, specify a 'top' file which would

- match on the MetalK8s version
- apply the states required to fulfill the 'roles'

An example of such `top.sls`:

```yaml
metalk8s-2.0:
  'metalk8s:version:2.0':
    - match: pillar
    - kubelet
    - calico
  'I@metalk8s:version:2.0 and I@metalk8s:role:bootstrap':
    - match: compound
    - repository
    - registry
  'I@metalk8s:version:2.0 and I@metalk8s:role:etcd':
    - match: compound
    - etcd
  'I@metalk8s:version:2.0 and I@metalk8s:role:master':
    - match: compound
    - control-plane
```

Every version can ship with such file, and since these are additive, we'd no longer need to specify `saltenv` for many operations.
