### ISSUE TITLE
kubelet service not restarted when kubeconfig changes

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#765]
When `/etc/kubernetes/kubelet.conf` is changed, the `kubelet` service isn't restarted to pick up these changes.

**Comment by NicolasT** [comment]
Context: I ran into a situation where Salt modified the file, but after this modification, `kubelet` was not restarted, and I had to do so manually for the changes to be applied.

Can't remember the exact scenario though :-/

**Comment by slaperche-scality** [comment]
Given the lack of scenario to reproduce it and the fact that it seems covered in the code (according to @TeddyAndrieux in Slack[1]) maybe we can close it as "Cannot reproduce" (and if it occurs again we can reopen it with more details) ?

----

[1]: 
> For me it's in `salt/metalk8s/kubeadm/init/kubeconfig/kubelet.sls`
> But the state should already restart kubelet
>
> ```yaml
> Restart kubelet:
>  service.running:
>    - name: kubelet
>    - enable: True
>    - watch:
>      - file: Configure kubelet service
>      - file: Ensure CA cert is present
>```

**Comment by NicolasT** [comment]
Well, `Configure kubelet service` is about `/etc/systemd/system/kubelet.service.d/10-metalk8s.conf`, and `Ensure CA cert is present` is about `/etc/kubernetes/pki/ca.crt`. However, Kubelet relies on `/var/lib/kubelet/kubeadm-flags.env` for `systemd` configuration (so would require `daemon-reload`), on `/var/lib/kubelet/config.yaml` for its own configuration, on `/etc/kubernetes/kubelet.conf` for its own authentication (the original cause for this ticket), and possibly other files. When those change, the service should pick up those changes (i.e. be restarted) as well, no?

**Comment by slaperche-scality** [comment]
Oh, so if I understand we would need to:

```yaml
    - watch:
      - file: Configure kubelet service
      - file: Ensure CA cert is present
+     - file: /var/lib/kubelet/kubeadm-flags.env
+     - file: /var/lib/kubelet/config.yaml
+     - file: /etc/kubernetes/kubelet.conf
```

Because changes to those files should trigger a restart when re-running the state.
