### ISSUE TITLE
Use K8s API instead of Salt's mine to know etcd cluster members

### ISSUE THREAD

**Issue by slaperche-scality** [scality/metalk8s#877]
This would be more reliable, for more info see Nicolas' comments:
- https://github.com/scality/metalk8s/issues/738#issuecomment-477364132
- https://github.com/scality/metalk8s/issues/738#issuecomment-477401597

**Comment by NicolasT** [comment]
We could either use the `Node` object, or alternatively, set up a (maybe headless, or not) `Service` for `etcd` backed by `Endpoint`s we create when setting up (or removing) `etcd` nodes (so, not using a 'dynamic' `Service` with a selector).

When using a non-headless service, we could then even access the cluster from the `salt-master` Pod (e.g. to perform `etcdctl`-style operations) by using the `ClusterIP`.

**Comment by TeddyAndrieux** [comment]
For me have it in mine make sense because if it's only in a pillar than mean each time we add a new etcd you need to refresh_pillar on **all** minions.
But have a custom pillar that retrieve informations from K8S to know if you (salt-minion server) are an etcd member it's ok for me. Also retrieve one or several IP and store it in pillar/mine make sense.

For me have something like that in the mine looks good:
```
bootstrap:
    etcd:
        cluster_ep: 10.0.0.1:2379
        real_ep: 192.168.1.101:2379
node1:
    etcd:
        cluster_ep: 10.0.0.2:2379
        real_ep: 192.168.1.102:2379
```
Make sense to you ?

But indeed do something when mine empty it's not a good idea.

Btw it's only my opinion, it's me who suggested to use mine but if you prefer use something else it's ok, as you want
