### ISSUE TITLE
Use Kubernetes 'service' objects for bootstrap service discovery

### ISSUE THREAD

**Issue by NicolasT** [scality/metalk8s#896]
We currently use a couple of hacks to find the addresses of services running on the bootstrap node (`salt-master`, registry,...).

Instead, we should

- [x] as part of the bootstrap process, create headless `Service` objects in the Kubernetes cluster which map to these services
- [ ] extend an `ext_pillar` to retrieve address(es) for these services and expose the information to the Salt states accordingly

The reason to use headless services: there's no real reason to assign a ClusterIP to these services because we won't have `kube-proxy` running on nodes at the time we need to be able to access these services.

**Comment by NicolasT** [comment]
@ramanduh Here's an example for `salt-master`:

The object:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: salt-master
  labels:
    app: salt-master
    app.kubernetes.io/name: salt-master
    app.kubernetes.io/component: salt
    heritage: metalk8s
    app.kubernetes.io/part-of: metalk8s
    app.kubernetes.io/managed-by: salt
spec:
  clusterIP: None
  ports:
  - name: publisher
    port: 4505
    protocol: TCP
    targetPort: publisher
  - name: requestserver
    port: 4506
    protocol: TCP
    targetPort: requestserver
  selector:
    app.kubernetes.io/component: salt
    app.kubernetes.io/name: salt-master
  type: ClusterIP
```
Apply it:
```
[root@bootstrap ~]# kubectl -n kube-system apply -f salt-master-service.yaml
service/salt-master created
```

Check result:
```
[root@bootstrap ~]# kubectl -n kube-system describe svc salt-master
Name:              salt-master
Namespace:         kube-system
Labels:            app=salt-master
                   app.kubernetes.io/component=salt
                   app.kubernetes.io/managed-by=salt
                   app.kubernetes.io/name=salt-master
                   app.kubernetes.io/part-of=metalk8s
                   heritage=metalk8s
Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"salt-master","app.kubernetes.io/component":"salt","app.kubernetes.io/...
Selector:          app.kubernetes.io/component=salt,app.kubernetes.io/name=salt-master
Type:              ClusterIP
IP:                None
Port:              publisher  4505/TCP
TargetPort:        publisher/TCP
Endpoints:         172.21.254.7:4505
Port:              requestserver  4506/TCP
TargetPort:        requestserver/TCP
Endpoints:         172.21.254.7:4506
Session Affinity:  None
Events:            <none>
```

See this list my `bootstrap` node's control-plane IP (i.e. the one Salt should be listening on) as one of the `Endpoints`. As such, we can now build a pillar module (or extend one of the existing ones) to retrieve this information and expose it to Salt Minions for usage in SLSs and templates and such.
